
import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/redux/Provider"
import Header from "@/components/header.component";
import { Poppins } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import Footer from "@/components/footer";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} min-h-screen`}
      >
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}


